version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
  app:
    build: .
    depends_on:
      - 'mysql'
    ports:
      - '3003:3003'
