version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
      - image: circleci/mysql:5.7.22-ram
          environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_DATABASE: items
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm test
